//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.03 at 02:43:37 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://github.com/taras-chornyi/bpel-process", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.taras.chornyi.bpel.connectors.domain;
